# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :hostonly, "33.33.0.4"
  config.vm.forward_port 80, 8080
  config.vm.forward_port 10081, 10081
  config.vm.forward_port 10082, 10082

  config.vm.share_folder "v-web-app", "/home/vagrant/app", "../../../php/"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.roles_path = "chef/roles"
    chef.add_role "server"
  end
end
